// Auth
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

// Clientes
export const GET_ALL_CLIENTES = "GET_ALL_CLIENTES";
export const OBTENER_CLIENTE = "OBTENER_CLIENTE";

// Grupos
export const GET_ALL_GRUPOS = "GET_ALL_GRUPOS";
export const OBTENER_GRUPO = "OBTENER_GRUPO";
export const ADD_GRUPOS = "ADD_GRUPOS";
export const UPDATE_GRUPOS = "UPDATE_GRUPOS";
export const DELETE_GRUPOS = "DELETE_GRUPOS";

// Tipo Cliente
export const GET_ALL_TIPO_CLIENTES = "GET_ALL_TIPO_CLIENTES";
export const OBTENER_TIPO_CLIENTE = "OBTENER_TIPO_CLIENTE";
export const ADD_TIPO_CLIENTES = "ADD_TIPO_CLIENTES";
export const UPDATE_TIPO_CLIENTES = "UPDATE_TIPO_CLIENTES";
export const DELETE_TIPO_CLIENTES = "DELETE_TIPO_CLIENTES";

// Marcas
export const GET_ALL_MARCAS = "GET_ALL_MARCAS";
export const OBTENER_MARCA = "OBTENER_MARCA";
export const ADD_MARCAS = "ADD_MARCAS";
export const UPDATE_MARCAS = "UPDATE_MARCAS";
export const DELETE_MARCAS = "DELETE_MARCAS";

// Regionales
export const GET_ALL_REGIONALES = "GET_ALL_REGIONALES";
export const OBTENER_REGIONAL = "OBTENER_REGIONAL";
export const ADD_REGIONALES = "ADD_REGIONALES";
export const UPDATE_REGIONALES = "UPDATE_REGIONALES";
export const DELETE_REGIONALES = "DELETE_REGIONALES";

//Puestos
export const GET_ALL_PUESTOS = "GET_ALL_PUESTOS";
export const OBTENER_PUESTO = "OBTENER_PUESTO";
export const ADD_PUESTOS = "ADD_PUESTOS";
export const UPDATE_PUESTOS = "UPDATE_PUESTOS";
export const DELETE_PUESTOS = "DELETE_PUESTOS";

//Departamentos
export const GET_ALL_DEPARTAMENTOS = "GET_ALL_DEPARTAMENTOS";
export const OBTENER_DEPARTAMENTO = "OBTENER_DEPARTAMENTO";
export const ADD_DEPARTAMENTOS = "ADD_DEPARTAMENTOS";
export const UPDATE_DEPARTAMENTOS = "UPDATE_DEPARTAMENTOS";
export const DELETE_DEPARTAMENTOS = "DELETE_DEPARTAMENTOS";
